# Generated by Django 4.0.1 on 2022-03-26 06:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='fooddata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodtype', models.CharField(default='', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('available', models.BooleanField(default=False)),
                ('message', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='foodpack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packName', models.CharField(default='', max_length=50)),
                ('food1', models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Corn', 'Corn'), ('Jowar', 'Jowar'), ('Bajri', 'Bajri'), ('Moong Dal', 'Moong Dal'), ('Masoor Dal', 'Masoor Dal'), ('Urad Dal', 'Urad Dal'), ('Chana Dal', 'Chana Dal'), ('Toor Dal', 'Toor Dal'), ('Rajma', 'Rajma'), ('Soy Bean', 'Soy Bean')], default='', max_length=50)),
                ('food2', models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Corn', 'Corn'), ('Jowar', 'Jowar'), ('Bajri', 'Bajri'), ('Moong Dal', 'Moong Dal'), ('Masoor Dal', 'Masoor Dal'), ('Urad Dal', 'Urad Dal'), ('Chana Dal', 'Chana Dal'), ('Toor Dal', 'Toor Dal'), ('Rajma', 'Rajma'), ('Soy Bean', 'Soy Bean')], default='', max_length=50)),
                ('food3', models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Corn', 'Corn'), ('Jowar', 'Jowar'), ('Bajri', 'Bajri'), ('Moong Dal', 'Moong Dal'), ('Masoor Dal', 'Masoor Dal'), ('Urad Dal', 'Urad Dal'), ('Chana Dal', 'Chana Dal'), ('Toor Dal', 'Toor Dal'), ('Rajma', 'Rajma'), ('Soy Bean', 'Soy Bean')], default='', max_length=50)),
                ('food4', models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Corn', 'Corn'), ('Jowar', 'Jowar'), ('Bajri', 'Bajri'), ('Moong Dal', 'Moong Dal'), ('Masoor Dal', 'Masoor Dal'), ('Urad Dal', 'Urad Dal'), ('Chana Dal', 'Chana Dal'), ('Toor Dal', 'Toor Dal'), ('Rajma', 'Rajma'), ('Soy Bean', 'Soy Bean')], default='', max_length=50)),
                ('quantity', models.CharField(default='', max_length=10)),
                ('available', models.BooleanField(default=False)),
                ('message', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('ngo', 'NGO'), ('doner', 'Doner'), ('consumer', 'consumer')], default='', max_length=10)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='userdetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(default='', max_length=50)),
                ('phoneno', models.CharField(default='', max_length=50)),
                ('aadhar', models.CharField(default='', max_length=50)),
                ('address', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=500)),
                ('state', models.CharField(default='', max_length=500)),
                ('zip', models.CharField(default='', max_length=50)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.myuser')),
            ],
        ),
        migrations.CreateModel(
            name='packCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default=0, max_length=10)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.cart')),
                ('foodpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.foodpack')),
            ],
        ),
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500)),
                ('pic', models.ImageField(null=True, upload_to='images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donate_date', models.DateTimeField(default=datetime.datetime.now)),
                ('foodtype', models.CharField(choices=[('Rice', 'Rice'), ('Wheat', 'Wheat'), ('Corn', 'Corn'), ('Jowar', 'Jowar'), ('Bajri', 'Bajri'), ('Moong Dal', 'Moong Dal'), ('Masoor Dal', 'Masoor Dal'), ('Urad Dal', 'Urad Dal'), ('Chana Dal', 'Chana Dal'), ('Toor Dal', 'Toor Dal'), ('Rajma', 'Rajma'), ('Soy Bean', 'Soy Bean')], default='', max_length=50)),
                ('quantity', models.IntegerField(default=0)),
                ('dateofc', models.DateField(default='')),
                ('timeofc', models.TimeField(default='')),
                ('address', models.CharField(default='', max_length=500)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.userdetail')),
            ],
        ),
        migrations.CreateModel(
            name='cartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default=0, max_length=10)),
                ('status', models.CharField(default='Pending', max_length=10)),
                ('order_date', models.DateTimeField(default=datetime.datetime.now)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.cart')),
                ('foodtype', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.fooddata')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.userdetail'),
        ),
    ]
