# Generated by Django 4.0.1 on 2022-01-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fooddonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodfor', models.CharField(choices=[('animal', 'ANIMAL'), ('human', 'HUMAN')], default='', max_length=7)),
                ('foodtype', models.CharField(default='', max_length=50)),
                ('quantity', models.CharField(default='', max_length=50)),
                ('dateofc', models.DateField(default='')),
                ('expdate', models.DateField(default='')),
                ('timeofc', models.TimeField(default='')),
                ('address', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(choices=[('ngo', 'NGO'), ('doner', 'Doner')], default='', max_length=5)),
                ('username', models.CharField(max_length=50)),
                ('email', models.CharField(default='', max_length=50)),
                ('phoneno', models.CharField(default='', max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
    ]
