# Generated by Django 4.0.1 on 2022-03-03 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='foodpack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packName', models.CharField(default='', max_length=50)),
                ('food1', models.CharField(default='', max_length=50)),
                ('food2', models.CharField(default='', max_length=50)),
                ('food3', models.CharField(default='', max_length=50)),
                ('food4', models.CharField(default='', max_length=50)),
                ('available', models.BooleanField(default=False)),
                ('message', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='packCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(default=0, max_length=10)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.cart')),
                ('foodpack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.foodpack')),
            ],
        ),
    ]
