# Generated by Django 4.0.1 on 2022-01-27 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='donatefoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodfor', models.CharField(choices=[('animal', 'ANIMAL'), ('human', 'HUMAN')], default='', max_length=7)),
                ('foodtype', models.CharField(default='', max_length=50)),
                ('quantity', models.CharField(default='', max_length=50)),
                ('dateofc', models.DateField(default='')),
                ('expdate', models.DateField(default='')),
                ('timeofc', models.TimeField(default='')),
                ('address', models.CharField(default='', max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='fooddonation',
        ),
    ]
