# Generated by Django 4.0.1 on 2022-03-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodForAll', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='gallarypics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pics', models.ImageField(upload_to='img')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FoodForAll.myuser')),
            ],
        ),
    ]
